name: Storybook Test
description: Storybook Test

runs:
  using: 'composite'
  steps:
    - name: Build storybook
      run: npm run build-storybook
      shell: bash
    - name: Storybook test
      run: npm run test-storybook:ci
      shell: bash
