name: Chromatic
description: Chromatic

runs:
  using: "composite"
  steps:
    - name: Move MSW file
      run: mv public/mockServiceWorker.js storybook-static
      shell: bash
    - name: Publish to Chromatic
      uses: chromaui/action@v1
      with:
        token: ${{ inputs.G_TOKEN }}
        projectToken: ${{ inputs.CHROMATIC_PROJECT_TOKEN }}
        storybookBuildDir: storybook-static
