name: Playwright setup from cache
description: Playwright setup from cache

runs:
  using: 'composite'
  steps:
    - uses: maxmilton/action-setup-playwright@v1
      with:
        browsers: chromium
        headless: true
