name: chromatic_merged

on:
  push:
    branches:
      - main
      - develop

jobs:
  chromatic_merged:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
      - name: Chromatic
        run: pnpm chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }}