name: Playwright Tests

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup
      uses: ./.github/actions/setup
    - name: Dev Database Reset
      uses: ./.github/actions/dev-database
    - name: Setup Playwright
      uses: ./.github/actions/playwright
    - name: Playwright test
      run: pnpm e2e
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
